# Generated by Django 6.0.5 on 2026-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0002_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='bas.book'),
        ),
    ]
